
# Package dependencies.
# Automatically generated by project defintion.

task "stx:libbasic2" => "stx:libbasic"

task "stx:libview2" => "stx:libbasic"
task "stx:libview2" => "stx:libview"
task "stx:libview2" => "stx:libbasic2"
task "stx:libview2" => "stx:libui"

task "stx:goodies/sunit" => "stx:libbasic"
task "stx:goodies/sunit" => "stx:libview2"
task "stx:goodies/sunit" => "stx:libbasic2"
task "stx:goodies/sunit" => "stx:libview"

task "stx:libview" => "stx:libbasic"
task "stx:libview" => "stx:libbasic2"


task "stx:libui" => "stx:libbasic"
task "stx:libui" => "stx:libview"

task "stx:libcomp" => "stx:libbasic"

task "cg:hdm/scheme2013" => "stx:goodies/sunit"
task "cg:hdm/scheme2013" => "stx:libbasic"
task "cg:hdm/scheme2013" => "stx:libcomp"


